language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  - g++ -std=c++17 -c application.cpp
  - g++ -std=c++17 -c database.cpp
  - g++ -std=c++17 -c table.cpp
  - g++ -std=c++17 -c record.cpp
  - g++ -std=c++17 -c instance.cpp
  - ar rscv libkeilo.a application.o database.o table.o record.o instance.o
  - g++ -std=c++17 main ./test/main.cpp ./libkeilo.a
  - ./main