language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  - g++ -c ./source/application.cpp -std=c++17 -lstdc++fs
  - g++ -c ./source/database.cpp -std=c++17 -lstdc++fs
  - g++ -c ./source/table.cpp -std=c++17 -lstdc++fs
  - g++ -c ./source/record.cpp -std=c++17 -lstdc++fs
  - g++ -c ./source/instance.cpp -std=c++17 -lstdc++fs
  - ar rscv libkeilo.a ./application.o ./database.o ./table.o ./record.o ./instance.o